use_frameworks!

target 'WGProjectConfig_Example' do
  pod 'WGProjectConfig', :path => '../'

  target 'WGProjectConfig_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
